export { default as Feed } from './Feed';
export { default as MovieID } from './MovieID';
export { default as MovieInfo } from './MovieInfo';
export { default as MovieCards } from './MovieCards';
export { default as NavBar } from './NavBar';
export { default as SearchBar } from './SearchBar';
export { default as SearchPage } from './SearchPage';
export { default as Footer } from './Footer';
export { default as NotFound } from './NotFound';